//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_has_Policy
    {
        public int id_coverage_plan { get; set; }
        public string plan_Coverage_description { get; set; }
        public string cover_object { get; set; }
        public int client_id_client { get; set; }
        public int policy_id_policy { get; set; }
        public System.DateTime coverage_start { get; set; }
        public int coverage_amount { get; set; }
        public int coverage_period { get; set; }
        public decimal coverage_monthly_price { get; set; }
        public int risk { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Policy Policy { get; set; }
    }
}
